baseURL = 'https://gfill.github.io/'
languageCode = 'en-us'
title = 'Guillem Foucault'
theme = 'gruvhugo'


#paginate = "10" # Number of posts per page

# enable shortcodes like css.inline
enableInlineShortcodes = true

# automatically updates last modified based on git
enableGitInfo = true


[frontmatter]
  lastmod = ['lastmod', ':git', 'date', 'publishDate']


# from gruvhugo
[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  headerTitle = "Guillem Foucault"
  name = "guillem_foucault"
 description = '''
  I am a PhD candidate at the <b>Toulouse School of economics</b>. My work covers topics related to <u>education and labor economics</u>. In particular, I am interested in how funding instruments and educational tracks affect students decisions and labour market outcomes.<br><br> 
  
  Don't hesitate to contact me at guillem.foucault[at]tse[slash]fr[dot]com.<br>
  
  <b>References:</b>
  <a href="https://sites.google.com/view/olivierdegroote">Olivier De Groote</a>, 
  <a href="https://sites.google.com/site/amgazmuri/home">Ana Gazmuri</a>
  '''
  licenseUrl = ""
 # homeContent = "content/_index"  # Add this line to specify the about page content for the home page
img = "images/profile.jpg"
 
 # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/gfill"


  [[params.social]]
    name = "email"
    url  = "mailto:guillem.foucault@tse-fr.eu"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mariebgl"


#[params.style]
  custom_scss = ["css/custom.scss"]

#[params.analytics]
#  goat_counter_link = #"https://samyak.goatcounter.com/count"

#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name       = "About"
#    url        = "about"

#  [[menu.main]]
#    identifier = "posts"
#    name       = "Blog"
#    url        = "post/"

#added an about me button which is the home page
[[menu.main]]
    identifier = "home"
    name       = "About"
    url        = ""

  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "research"

  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "cv"

  [[menu.main]]
    identifier = "teaching"
    name       = "Teaching"
    url        = "teaching"

#  [[menu.main]]
#    identifier = "ressources"
#    name       = "Ressources"
#    url        = "ressources"

[permalinks]
  post = '/:section/:slug'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
